bedroom_choices = {
"1":1,
"2":2,
"3":3,
"4":4,
"5":5,
"6":6,
"7":7,
"8":8,
"9":9,
"10":10,
}

price_choices =  {
        "100000":  "$100,000",
        "200000":  "$200,000",
        "300000":  "$300,000",
        "400000":  "$400,000",
        "500000":  "$500,000",
        "600000":  "$600,000",
        "700000":  "$700,000",
        "800000":  "$800,000",
        "900000":  "$900,000",
        "1000000": "$1M+",
}

state_choices = {

        "AL": "Alabama",
        "AK": "Alaska",
        "AZ": "Arizona",
        "AR": "Arkansa",
        "CA": "Califoron",
        "CO": "Colorad",
        "CT": "Connection",
        "DE": "Delawar",
        "DC": "Districmbia",
        "FL": "Florida",
        "GA": "Georgia",
        "HI": "Hawaii",
        "ID": "Idaho",
        "IL": "Illinoi",
        "IN": "Indiana",
        "IA": "Iowa",
        "KS": "Kansas",
        "KY": "Kentuck",
        "LA": "Louisian",
        "ME": "Maine",
        "MD": "Marylan",
        "MA": "Massachption",
        "MI": "Michiga",
        "MN": "Minneson",
        "MS": "Missission",
        "MO": "Missour",
        "MT": "Montana",
        "NE": "Nebrask",
        "NV": "Nevada",
        "NH": "New Hamption",
        "NJ": "New Jeron",
        "NM": "New Mexon",
        "NY": "New Yor",
        "NC": "North Coption",
        "ND": "North Dtion",
        "OH": "Ohio",
        "OK": "Oklahom",
        "OR": "Oregon",
        "PA": "Pennsyltion",
        "RI": "Rhode Ition",
        "SC": "South Coption",
        "SD": "South Dtioon",
        "TN": "Tennessn",
        "TX": "Texas",
        "UT": "Utah",
        "VT": "Vermont",
        "VA": "Virgini",
        "WA": "Washingon",
        "WV": "West Viption",
        "WI": "Wisconsn",
        "WY": "Wyoming",

}